### ISSUE TITLE
Перенос на react страницы с картой

### ISSUE THREAD

**Issue by GreoGi** [map-sharing/web#1]

**Comment by ololo-zen** [comment]
Тут надо уточнить: карту как таковую на реакт уже перенесли, задачу можно закрыть. Если мы хотим перенести на реакт все соответствующие компоненты (а-ля хедер, панельку создания точек, панельку регистрации, панельку авторизации и т.д), то либо пункты в задаче надо расписать соответствующие, либо отдельные ишью под них делать.
